### ISSUE TITLE
Refresh option only available for projects

### ISSUE THREAD

**Issue by DaveCarpeneto** [eclipse-platform/eclipse.platform.ui#1904]
- [X] I verified I can reproduce this issue against [latest Integration Build of Eclipse SDK](https://download.eclipse.org/eclipse/downloads/)

Reporting this against Eclipse IDE for Java Developers, Version: 2024-03 (4.31.0), Build id: 20240307-1437 ( https://www.eclipse.org/downloads/download.php?file=/technology/epp/downloads/release/2024-03/R/eclipse-java-2024-03-R-win32-x86_64.zip )

This situation is *NOT* seen in the previous quarterly release (Version: 2023-12 (4.30.0), Build id: 20231201-2043), and I don't see anything mentioned regarding this functionality @ https://eclipse.dev/eclipse/news/4.31/ . As such I'm guessing this is a bug.

I'm using Eclipse on Windows. 

## Steps to reproduce

A plugin that I work on has a view that extends org.eclipse.ui.navigator.CommonNavigator . In previous versions this provided 'Refresh (F5)' in the contextual menu for any resource. However as of 2024-03 the mentu option only exists for projects, but not other resources. 

Fairly easy to trigger / reproduce. Plug-in Spy tells me the following for the menu entry I'm talking about here:

![oldEclipseOScript](https://github.com/eclipse-platform/eclipse.platform.ui/assets/32582337/f41a2eb9-5b22-48a4-9ebc-6f1864d6eaf8)

... I tried to quickly look through things based on this, but I'm not smart enough to see what might be the cause of this. 

## Community

- [X] I understand reporting an issue to this OSS project does not mandate anyone to fix it. Other contributors may consider the issue, or not, at their own convenience. The most efficient way to get it fixed is that I fix it myself and contribute it back as a good quality patch to the project.

**Comment by iloveeclipse** [comment]
Please try with 4.32 RC2: https://download.eclipse.org/eclipse/downloads/drops4/I20240529-1800

**Comment by DaveCarpeneto** [comment]
@iloveeclipse : unfortunately still an issue :-(

**Comment by DaveCarpeneto** [comment]
OK, a very kind & intelligent coworker spotted where the change was introduced: https://github.com/eclipse-platform/eclipse.platform/issues/876 

... this change means that the 'refresh' option is now only shown for open projects (prior to this change refresh was shown unless one of the selections was a closed project).

So if refresh was indeed intended to be project-only, then this change results in the 'correct' behavior. 

If however the Eclipse project would rather continue to allow the refresh menu item for all resources (which is how the JDT plugin des things in the 'Package Explorer' view, and is super-helpful when you have a massive project & you're only looking to refresh a small section) then further changes to bundles/org.eclipse.ui.navigator.resources/src/org/eclipse/ui/internal/navigator/resources/actions/ResourceMgmtActionProvider.java would be appreciated, perhaps the following: 

     -	// To refresh, even if one project is open
     -	if (hasOpenProjects) {
     +	// To refresh if any selection is (a) an open project, or (b) a non-project
     +	if (hasOpenProjects || !isProjectSelection) {
			refreshAction.selectionChanged(selection);
			menu.appendToGroup(ICommonMenuConstants.GROUP_BUILD, refreshAction);
		}

... thoughts? I've not got an environment over here that's convenient to test this, but to me it makes sense & largely allows for the old behavior whilst simultaneously retaining the fix introduced by @vogella via the aforementioned ticket.

**Comment by iloveeclipse** [comment]
Please provide a PR

**Comment by merks** [comment]
It's really easy to set up a development environment automatically via the link there:

https://github.com/eclipse-platform/.github/blob/main/CONTRIBUTING.md#creating-an-eclipse-development-environment

**Comment by DaveCarpeneto** [comment]
Thanks @merks for the link; I'm just checking with my manager as to what legal hoops I need to jump through before I'm allowed to attempt to contribute here.

**Comment by iloveeclipse** [comment]
Is this fixed via https://github.com/eclipse-platform/eclipse.platform.ui/pull/2003? Please close if that is the case.

**Comment by c-delanneau** [comment]
Hello, the problem is still present for me.
I'm on version 2024-09 of Eclipse and I found the code updated by the PR in the package `org.eclipse.ui.navigator.resources_3.9.400.v20240722-1923.jar`, however the 'Refresh (F5)' menu still doesn't appear when I select a resource in an open project.
Does this work correctly for you?

**Comment by DaveCarpeneto** [comment]
@c-delanneau : no - the fix I submitted was partial. I'm currently getting approval from my org to submit a revised fix. Apologies for the impact on this.

**Comment by DaveCarpeneto** [comment]
As mentioned above, the fix initially checked in was a partial fix. Further changes are needed to resolve this issue.

**Comment by DaveCarpeneto** [comment]
Closing, since I've opened https://github.com/eclipse-platform/eclipse.platform.ui/issues/2492 as a new issue so that it gets picked up my project admins.
