### ISSUE TITLE
[Eclipse 4.25 Dark Theme] View action buttons are not highlighted

### ISSUE THREAD

**Issue by wolfgang-ch** [eclipse-platform/eclipse.platform.ui#340]
There are 2 dark theme issues in Eclipse 4.25

* A selected button is not highlighted (red box) in the view toolbar, 4.24 has a blue border around the action button. The green boxes are showing the correct button highlights
* The toolbar has a brighter grey background (pink boxes)

![image](https://user-images.githubusercontent.com/1283445/190892508-852be692-6f0d-45b8-9b77-67a7e5adccbb.png)

The same buttons in Eclipse 4.24 

![image](https://user-images.githubusercontent.com/1283445/190892490-db6621cf-9494-4d19-9c1e-a078bf7a182c.png)

**Comment by RoiSoleil** [comment]
Any news about that ?

**Comment by akurtakov** [comment]
As it can be seen by lack of progress here - some help is needed for dark theme issues.  Do you think you can try identifying the issue?

**Comment by wolfgang-ch** [comment]
The UI with this fix https://github.com/eclipse-platform/eclipse.platform.swt/issues/541#issuecomment-1521695639 is now better but still not very good visible

![image](https://user-images.githubusercontent.com/1283445/236403049-86b2f1da-f011-44dd-b747-b373549c3dbd.png)

**Comment by trancexpress** [comment]
See also #467, #468, #648.

**Comment by pbodnar** [comment]
Great to see this annoying bug is finally fixed now in 4.28 (2023-06)! A bit surprised this didn't make it into the N&N, but whatever. ;)

Here are my 2 cents:

> The UI with this fix [eclipse-platform/eclipse.platform.swt#541 (comment)](https://github.com/eclipse-platform/eclipse.platform.swt/issues/541#issuecomment-1521695639) is now better but still not very good visible
> 
> ![image](https://user-images.githubusercontent.com/1283445/236403049-86b2f1da-f011-44dd-b747-b373549c3dbd.png)

@wolfgang-ch, I would say it depends... Anyway, I would suggest to close this issue as resolved and if desired, open a new one for _improving_ the existing highlighting.

-----

> See also #467, #468, #648.

@trancexpress, yes, #467 and #648 seem like clear duplicates of this one. At least, I cannot see any difference. Anyone willing to close them? (maybe a typical "checklist" added to "new issue template" would help to avoid such duplicates?)

Regarding #468, it seems to be about something else (to quote from a comment there: "ignoring the push toggle buttons... a separate issue entirely").

Also there is this #306 created even before this one, but it is way too technical for me to be able to efficiently evaluate whether it is a duplicate as well...

**Comment by wolfgang-ch** [comment]
>@wolfgang-ch, I would say it depends... Anyway, I would suggest to close this issue as resolved and if desired, open a new one for improving the existing highlighting.

The checked actions are now as before 😄 but I still see the second issue

> The toolbar has a brighter grey background (pink boxes)

![image](https://github.com/eclipse-platform/eclipse.platform.ui/assets/1283445/a63013b1-b2a6-417e-b6f1-348ee764d197)

**Comment by pbodnar** [comment]
> The checked actions are now as before 😄 but I still see the second issue
> 
> > The toolbar has a brighter grey background (pink boxes)
> 
> ![image](https://user-images.githubusercontent.com/1283445/247606628-a63013b1-b2a6-417e-b6f1-348ee764d197.png)

Oh, I see. The "pink boxes" from the description screenshot. Maybe this is done on purpose? I have no idea. :) Anyway, the issue title says "View action buttons are not highlighted" and _that_ got resolved, so better create a new issue? :)

**Comment by mrx23dot** [comment]
I've got another issue with dark theme, not sure if it needs new ticket:
whenever I select a menu it's unreadable
![2023-08-29_230051_lQ](https://github.com/eclipse-platform/eclipse.platform.ui/assets/4163396/d3727124-70c7-46fd-949e-32a6c6e56c16)

![2023-08-29_232112_kw](https://github.com/eclipse-platform/eclipse.platform.ui/assets/4163396/ac8c223e-0f9b-41d3-89ee-a03f429fa5a0)

Version: 2023-06 (4.28.0)
Build id: 20230608-1333

**Comment by RoiSoleil** [comment]
This a completely different bug.

**Comment by vogella** [comment]
AFAICS this is solved in latest dark theme changes by @mvm-sap. Please test with latest I-Build from https://download.eclipse.org/eclipse/downloads/.
