### ISSUE TITLE
PartRenderingEngineTests.ensureCleanUpAddonCleansUp still fails randomly

### ISSUE THREAD

**Issue by ptziegler** [eclipse-platform/eclipse.platform.ui#3581]
https://github.com/eclipse-platform/eclipse.platform.ui/runs/57884315250

```
CleanupAddon should ensure that partStack is not rendered anymore, as all childs have been removed
java.lang.AssertionError: CleanupAddon should ensure that partStack is not rendered anymore, as all childs have been removed
	at org.junit.Assert.fail(Assert.java:89)
	at org.junit.Assert.assertTrue(Assert.java:42)
	at org.eclipse.e4.ui.tests.workbench.PartRenderingEngineTests.ensureCleanUpAddonCleansUp(PartRenderingEngineTests.java:2472)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.eclipse.e4.ui.tests.rules.WorkbenchContextRule$1.evaluate(WorkbenchContextRule.java:62)
	Suppressed: java.lang.Throwable: Screenshot written to C:\Users\RUNNER~1\AppData\Local\Temp\org.eclipse.e4.ui.tests.workbench.PartRenderingEngineTests.ensureCleanUpAddonCleansUp.png
		at org.eclipse.test.Screenshots$ScreenshotOnFailure.failed(Screenshots.java:41)
AWT screenshot saved to: C:\Users\RUNNER~1\AppData\Local\Temp\org.eclipse.e4.ui.tests.workbench.PartRenderingEngineTests.ensureCleanUpAddonCleansUp.png
```

The test failure can be reproduced locally (on Linux at least) after executing the test ~30-70 times.

See:
- https://github.com/eclipse-platform/eclipse.platform.ui/commit/64500cdcaf3233b8f368674d01b39b010db7af67
- https://github.com/eclipse-platform/eclipse.platform.ui/commit/7a24db1a216ef1e9940840c7c1156e1f9a82fc93
- https://github.com/eclipse-platform/eclipse.platform.ui/commit/a3fa06583905e66550c0b4e8a3961320cfb4ca43
- https://github.com/eclipse-platform/eclipse.platform.ui/issues/751

**Comment by vogella** [comment]
[Check warning on line 0 in UIAllTests PartRenderingEngineTests](https://github.com/eclipse-platform/eclipse.platform.ui/commit/d6fda4278f3b5a718dc36354c52b2a1013ad87d3#annotation_45115663133) 

@github-actions
github-actions
/ Test Results
1 out of 3 runs failed: ensureCleanUpAddonCleansUp (UIAllTests PartRenderingEngineTests)

artifacts/test-results-macos-14/tests/org.eclipse.e4.ui.tests/target/surefire-reports/TEST-org.eclipse.e4.ui.tests.workbench.PartRenderingEngineTests.xml [took 30s]
CleanupAddon should ensure that partStack is not rendered anymore, as all childs have been removed ==> expected: <true> but was: <false>
org.opentest4j.AssertionFailedError: CleanupAddon should ensure that partStack is not rendered anymore, as all childs have been removed ==> expected: <true> but was: <false>
	at org.junit.jupiter.api.AssertionFailureBuilder.build(AssertionFailureBuilder.java:151)
	at org.junit.jupiter.api.AssertionFailureBuilder.buildAndThrow(AssertionFailureBuilder.java:132)
	at org.junit.jupiter.api.AssertTrue.failNotTrue(AssertTrue.java:63)
	at org.junit.jupiter.api.AssertTrue.assertTrue(AssertTrue.java:36)
	at org.junit.jupiter.api.Assertions.assertTrue(Assertions.java:214)
	at org.eclipse.e4.ui.tests.workbench.PartRenderingEngineTests.ensureCleanUpAddonCleansUp(PartRenderingEngineTests.java:2453)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)

**Comment by trancexpress** [comment]
Lets keep this open until the fix is merged: https://github.com/eclipse-platform/eclipse.platform.ui/pull/3786

**Comment by tobiasmelcher** [comment]
The test error still occurs on linux in https://github.com/eclipse-platform/eclipse.platform.ui/pull/3868/checks?check_run_id=70208650857 . Could you please help?

**Comment by vogella** [comment]
That is annoying. Re-run the test in this case, it is flaky, so this only happens sometimes
